# Generated by Django 4.2.17 on 2024-12-09 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userclass',
            options={'verbose_name': 'Ocupación de usuario', 'verbose_name_plural': 'Ocupaciones de usuario'},
        ),
    ]
