# Generated by Django 5.1.3 on 2024-12-09 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_userclass_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userclass',
            name='ocupacion',
            field=models.TextField(choices=[('bodeguero', 'Bodeguero'), ('jefe de Inventario', 'Jefe de Inventario')], max_length=20, verbose_name='Ocupación'),
        ),
    ]
