# Generated by Django 5.1.3 on 2024-12-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockList', '0003_alter_tables_calificacion_alter_tables_codprod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tables',
            name='calificacion',
            field=models.TextField(choices=[('Original', 'Original'), ('Marca alterna', 'Marca alterna')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tables',
            name='tipoProd',
            field=models.TextField(max_length=13),
        ),
    ]
