# Generated by Django 4.2.17 on 2024-12-09 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockList', '0005_alter_tables_calificacion_alter_tables_nomprod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tables',
            name='calificacion',
            field=models.TextField(choices=[('Original', 'Original'), ('Marca alterna', 'Marca alterna')], max_length=20, verbose_name='Calificación'),
        ),
    ]
